title: Run production-grade databases easily on Kubernetes
baseurl: https://kubedb.com
languageCode: en-us
pluralizeListTitles: false
pygmentsStyle: "monokai"
pygmentsUseClasses: false
disqusShortname: appscode
staticdir: "build"
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
params:
  author: KubeDB Authors
  date_format: Mon, Jan 2, 2006
  description: Run production-grade databases easily on Kubernetes
  email: support@appscode.com
  logo: /images/logo.svg
  twitter_url: https://twitter.com/KubeDB
  facebook_url: https://www.facebook.com/appscode
  github_url: https://github.com/k8sdb
  docker_url: https://hub.docker.com/u/kubedb
  youtube_url: https://www.youtube.com/c/appscode
  contact_email: support@appscode.com
  sales_email: sales@appscode.com
  contact_phone: +1 (650) 241-8486
menu:
  main:
      - Name: "Install"
        Weight: 1
        URL: https://github.com/k8sdb/cli/blob/master/docs/install.md
      - Name: "Tutorials"
        Weight: 2
        URL: https://github.com/k8sdb/cli/tree/master/docs/tutorials
      - Name:
        Pre: "<i class='fa fa-github'></i>"
        Weight: 3
        Identifier: "GitHub"
        URL: "https://github.com/k8sdb/cli#kubedb"
      - Name:
        Pre: "<i class='fa fa-twitter'></i>"
        Weight: 4
        Identifier: "twitter"
        URL: "https://twitter.com/KubeDB"
      - Name:
        Pre: "<i class='fa fa-slack'></i>"
        Weight: 5
        Identifier: "slack"
        URL: "http://slack.kubernetes.io/"
