title: All-In-One Application Development Platform
baseurl: https://appscode.com/
languageCode: en-us
pluralizeListTitles: false
pygmentsStyle: "monokai"
pygmentsUseClasses: false
disqusShortname: appscode
staticdir: "build"
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
params:
  author: AppsCode Team
  date_format: Mon, Jan 2, 2006
  description: Integrated platform for collaborative coding, testing & deploying containerized apps
  ga_id: UA-62096468-4
  tagmanager_id: GTM-52KJSD
  email: support@appscode.com
  logo: /images/logo.svg
  twitterstatus_url: https://twitter.com/AppsCodeStatus
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  github_url: https://github.com/appscode
  docker_url: https://hub.docker.com/u/appscode
  youtube_url: https://www.youtube.com/c/appscode
  contact_email: support@appscode.com
  sales_email: sales@appscode.com
  contact_phone: +1 (650) 241-8486
